### ISSUE TITLE
clarify cell 1

### ISSUE THREAD

**Issue by jovo** [neurodata/extensible-science-paper#42]
what is happening that is taking 3-4 minutes?
seems like most of it is downloading?
does it make sense to break it up into multiple cells?

**Comment by jovo** [comment]
i think it might be instructive if it were broken up into 2 cells:
1. download
2. process

to give people a sense of how long it takes to do each of them?

**Comment by gkiar** [comment]
Download takes only 10 seconds or so, most of the time is the processing. It's currently in 1 cell because it is literally running the demo script which pulls data and computes it (because in practice people wanting the demo want to type 1 line rather than 2).

In my opinion it doesn't make sense to separate, but what do you think/want? I can make *anything* happen. :)

**Comment by jovo** [comment]
I see.
Maybe just say download takes 10 sec to clarify?
Maybe link to pipeline schematic , so people know the steps that are
happening?
